# Generated by Django 4.1.4 on 2023-03-08 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('feedback', models.TextField()),
            ],
        ),
    ]
